### ISSUE TITLE
Can't pair the controller with IOS

### ISSUE THREAD

**Issue by Cfirote** [Ximmerse/SDK_Flip#1]
Hi,

i have compile the "01 - Device Test" for IOS and build the application

it work on iPhone but impossible to connecte the controller with the Iphone (on Android we have an utility to pair the controller, and the bluetooth doesn't dettect it)

do you have any solution to pair it on IOS ?

Regards.

**Comment by yifu-ximmerse** [comment]
Hi, there,
Our plugin works different on iOS platform vs Android. 
On Android, you would need to use an pairing application to pair the controllers.
However,
on iOS, all you need to do is turn on your controller before you run the app, no separate pairing app and there is no pairing process. 
The iOS app will automatically search and connect the first device that matches the “parameters”.

Yifu

**Comment by Cfirote** [comment]
that Works, thanks a lot :D
